name: Node.js Package

on:
 [push]

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: 'Sending SMS Notification'
       uses: twilio-labs/actions-sms@v1
       with:
         fromPhoneNumber: ${{ secrets.TWILIO_PHONE_NUMBER }}
         toPhoneNumber: ${{ secrets.MY_PHONE_NUMBER }}
         message: 'The latest version of your package has been shipped 🎉'
       env:
         TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
         TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
         TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
